FEM-2237 Add configuration for track selection to select multiple tracks so it works as ABR
kaltura/playkit-android pull request #523
Opened 2019-02-05 09:10 UTC by GouravSna

- Use Player settings to define min max ABR 
- `setInitialBitrateEstimate` in Settings

```
player.getSettings().setMaxVideoBitrate(659844);
player.getSettings().setMinVideoBitrate(132620);
player.getSettings().setInitialBitrateEstimate(277528);
```

2019-02-05 14:01 UTC, OrenMe requested changes

2019-02-05 14:01 UTC, OrenMe commented on playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java
> +            if (videoTracks.size() >= 2) {
this code repeats itself in the wrapper as well, may be better to expose error from the trackSelector and listen in wrapper instead of repeating it

2019-02-06 10:11 UTC, OrenMe approved these changes

2019-02-06 10:13 UTC, giladna approved these changes

2019-02-06 10:30 UTC, merged